Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,13 +1,32 @@
-# You can override the included template(s) by including variable overrides
-# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
-# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
-# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
-# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
-# Note that environment variables can be set in several places
-# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
 stages:
-- test
-sast:
-  stage: test
-include:
-- template: Security/SAST.gitlab-ci.yml
+  - check-package-json
+ 
+check-package-json:
+  stage: check-package-json
+  before_script:
+    - apt-get update && apt-get install -y jq
+  script:
+    |
+      git fetch origin $CI_COMMIT_BRANCH
+      git checkout $CI_COMMIT_BRANCH
+      PREVIOUS_PACKAGE_JSON=$(git show origin/$CI_COMMIT_BRANCH~1:package.json)
+      CURRENT_PACKAGE_JSON=$(cat package.json)
+      PREVIOUS_DEPS=$(echo "$PREVIOUS_PACKAGE_JSON" | jq -r '.dependencies | keys[]')
+      CURRENT_DEPS=$(echo "$CURRENT_PACKAGE_JSON" | jq -r '.dependencies | keys[]')
+ 
+      for dep in $PREVIOUS_DEPS; do
+        if ! echo "$CURRENT_DEPS" | grep -qw "$dep"; then
+          echo "$dep is missing in the package.json file "
+          exit 1
+        fi
+      done
+ 
+      NEW_DEPS=$(comm -13 <(echo "$PREVIOUS_DEPS" | sort) <(echo "$CURRENT_DEPS" | sort))
+      if [ -n "$NEW_DEPS" ]; then
+        echo "New dependencies added:"
+        for dep in $NEW_DEPS; do
+          echo "- $dep"
+        done
+      else
+        echo "No modifications have been made to package.json"
+      fi
